theme = "base16_transparent"

[editor]
line-number = "relative"
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = []
right = ["mode"]
mode.normal = "ﮂ "
mode.insert = "פֿ "
mode.select = "﬍ "
# left = ["mode", "file-name"]
# right = ["file-type", "spinner"]